name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Figure out correct username
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }}"
      - name: Auto-merge PR
        if: github.actor == 'devin-ai-integration[bot]'
        uses: KeisukeYamashita/auto-pull-request-merge@v1

